complete -c nq -s h -d 'Show brief help'
complete -c nq -l help -d 'Show full or topic help' -xa 'help query catalog cache use-cache clear-cache list-caches connection output parameters parquet'
complete -c nq -l version -d 'Show NQ version'
complete -c nq -s p -r -d 'Read JDBC properties' -F
complete -c nq -s i -l input -r -d 'Read typed standard input' -xa 'json jsonl yaml xml csv parquet'
complete -c nq -s o -l output -r -d 'Select output format' -xa 'json jsonl yaml xml csv markdown'
complete -c nq -l debug -d 'Enable debug diagnostics'
complete -c nq -l no-key-inference -d 'Disable query-output key inference'
complete -c nq -s c -l cache -d 'Materialize input in a persistent cache'
complete -c nq -l cache-dir -r -d 'Select cache directory' -a '(__fish_complete_directories)'
complete -c nq -l use-cache -r -d 'Activate an existing cache' -F
complete -c nq -l list-caches -d 'List persistent caches'
complete -c nq -l clear-cache -r -d 'Clear caches' -F
complete -c nq -l clear-cache-older-than -r -d 'Clear caches older than an age'
complete -c nq -l anonymous-collections -r -d 'Select anonymous collection policy' -xa 'merge error'
complete -c nq -l relation-alias -r -d 'Map source path to relation name'
complete -c nq -l metadata-refresh -d 'Refresh database key metadata'
complete -c nq -l metadata-expiry-hours -r -d 'Set metadata expiry hours'
complete -c nq -l parquet-root -r -d 'Override Parquet hierarchy root'
complete -c nq -l parquet-record -r -d 'Override Parquet record name'
complete -c nq -l db -r -d 'Select logical database driver' -xa 'h2 mysql mariadb postgresql oracle sqlserver db2 hana informix'
complete -c nq -l database -r -d 'Select database name or H2 URL suffix'
complete -c nq -l host -r -d 'Select database host'
complete -c nq -l port -r -d 'Select database port'
complete -c nq -l user -r -d 'Select database username'
complete -c nq -l password -r -d 'Select database password'
complete -c nq -l jdbc-driver -r -d 'Select exact logical JDBC driver' -xa 'h2 mysql mariadb postgresql oracle sqlserver db2 hana informix'
complete -c nq -l jdbc-class-name -r -d 'Select JDBC class'
complete -c nq -l jdbc-database -r -d 'Select JDBC URL'
complete -c nq -l jdbc-username -r -d 'Select JDBC username'
complete -c nq -l jdbc-password -r -d 'Select JDBC password'
