complete -c nq -f
complete -c nq -n '__fish_use_subcommand' -a 'run convert catalog cache help'
complete -c nq -n '__fish_seen_subcommand_from cache' -a 'load use list clear'
complete -c nq -s h -d 'Show brief help'
complete -c nq -l help -d 'Show full or topic help'
complete -c nq -l version -d 'Show NQ version'
complete -c nq -l script-file -r -d 'Read script file' -F
complete -c nq -l script-text -r -d 'Use inline script text'
complete -c nq -l input-file -r -d 'Read input file or -' -F
complete -c nq -l input-format -r -d 'Name stdin format' -xa 'json jsonl yaml xml csv tsv toml parquet'
complete -c nq -l param -r -d 'Set template parameter'
complete -c nq -s p -l properties -r -d 'Read properties' -F
complete -c nq -s o -l output -r -d 'Select result format' -xa 'json jsonl yaml xml csv tsv toml markdown'
complete -c nq -l report-format -r -d 'Select report format' -xa 'json jsonl yaml xml csv tsv toml markdown'
complete -c nq -l state-dir -r -d 'Select state root' -a '(__fish_complete_directories)'
complete -c nq -l cache -d 'Persist run input'
complete -c nq -l pattern -r -d 'Select catalog pattern'
complete -c nq -l name -r -d 'Select cache name'
complete -c nq -l all -d 'Select all caches'
complete -c nq -l older-than -r -d 'Select cache age'
complete -c nq -l debug -d 'Enable debug diagnostics'
complete -c nq -l no-key-inference -d 'Disable query-output key inference'
complete -c nq -l parquet-root -r -d 'Override Parquet root'
complete -c nq -l parquet-record -r -d 'Override Parquet record'
complete -c nq -l db -r -d 'Select logical database driver' -xa 'h2 mysql mariadb postgresql oracle sqlserver db2 hana informix'
complete -c nq -l database -r -d 'Select database'
complete -c nq -l host -r -d 'Select host'
complete -c nq -l port -r -d 'Select port'
complete -c nq -l user -r -d 'Select username'
complete -c nq -l password -r -d 'Select password'
complete -c nq -l jdbc-driver -r -d 'Select JDBC driver'
complete -c nq -l jdbc-class-name -r -d 'Select JDBC class'
complete -c nq -l jdbc-database -r -d 'Select JDBC URL'
complete -c nq -l jdbc-username -r -d 'Select JDBC username'
complete -c nq -l jdbc-password -r -d 'Select JDBC password'
