complete -c nql -f
complete -c nql -n '__fish_use_subcommand' -a 'run convert catalog cache capabilities help version'
complete -c nql -n '__fish_seen_subcommand_from cache' -a 'load use list clear'
complete -c nql -s h -d 'Show brief help'
complete -c nql -l help -d 'Show full or topic help'
complete -c nql -l version -d 'Show NQL version'
complete -c nql -l capabilities -d 'Print machine-readable capability contract'
complete -c nql -s f -l script-file -r -d 'Read script file' -F
complete -c nql -s e -l script-text -r -d 'Use inline script text'
complete -c nql -s i -l input-file -r -d 'Read input file or -' -F
complete -c nql -s t -l input-format -r -d 'Name stdin format' -xa 'json jsonl yaml xml csv tsv toml parquet'
complete -c nql -l param -r -d 'Set task parameter'
complete -c nql -l params-file -r -d 'Read task parameters' -F
complete -c nql -l config -r -d 'Read operational configuration' -F
complete -c nql -s o -l output -r -d 'Select result format' -xa 'json jsonl yaml xml csv tsv toml markdown'
complete -c nql -s r -l report-format -r -d 'Select report format' -xa 'json jsonl yaml xml csv tsv toml markdown'
complete -c nql -l cache-dir -r -d 'Select direct cache directory' -a '(__fish_complete_directories)'
complete -c nql -l cache -d 'Select cache execution'
complete -c nql -s m -l pattern -r -d 'Select catalog pattern'
complete -c nql -l name -r -d 'Select cache name'
complete -c nql -l all -d 'Select all caches'
complete -c nql -l older-than -r -d 'Select cache age'
complete -c nql -l debug -d 'Enable debug diagnostics'
complete -c nql -l no-key-inference -d 'Disable query-output key inference'
complete -c nql -l parquet-root -r -d 'Override Parquet root'
complete -c nql -l parquet-record -r -d 'Override Parquet record'
complete -c nql -l db -r -d 'Select logical database driver' -xa 'h2 mysql mariadb postgresql oracle sqlserver db2 hana informix'
complete -c nql -l database -r -d 'Select database'
complete -c nql -l host -r -d 'Select host'
complete -c nql -l port -r -d 'Select port'
complete -c nql -l user -r -d 'Select username'
complete -c nql -l password -r -d 'Select password'
complete -c nql -l jdbc-driver -r -d 'Select JDBC driver'
complete -c nql -l jdbc-class-name -r -d 'Select JDBC class'
complete -c nql -l jdbc-database -r -d 'Select JDBC URL'
complete -c nql -l jdbc-username -r -d 'Select JDBC username'
complete -c nql -l jdbc-password -r -d 'Select JDBC password'
