#!/usr/bin/env bash
fatal() {
  echo "$1"; exit 1
}
DATAFILE="data/wikidata-companies.json"
STATE_DIR="data/state"

## cd "$(dirname "$0")"
if [ "$1" = "" -o "$1" = "-h" ]; then
  ../target/nq --help
  exit 0
fi

SCRIPTFILE="$1"
[[ ! -f $SCRIPTFILE ]] && fatal "File [$SCRIPTFILE] not found"


../target/nq run \
  --script-file "$SCRIPTFILE" \
  --input-file "$DATAFILE" \
  --cache \
  --state-dir "$STATE_DIR"
